### ISSUE TITLE
New feature: add option to open logcat

### ISSUE THREAD

**Issue by okwasniewski** [okwasniewski/MiniSim#106]
The goal of this issue is to add option to launch logcat for each device separately. 

Logcat should launch with `-v color` flag. This feature should also take into account user's preferred terminal (iTerm, Terminal.app etc.) 

This was currently achievable through custom commands but _native_ support would increase the use of this feature

**Comment by gokul1099** [comment]
@okwasniewski  Shall I work on this

**Comment by okwasniewski** [comment]
@gokul1099 Sure! Go ahead

**Comment by gokul1099** [comment]
@okwasniewski  users preferred terminal means, whether the terminal the user set as default terminal or we have to ask the user to select the terminal they prefer to open the logcat

**Comment by okwasniewski** [comment]
I would keep an option in Preferences which dropdown for `iTerm.app`, `Terminal.app` and others but I think we can implement it in the next iteration. So firstly let's implement this feature as a whole (keeping in mind that in the future we will change the terminal we are launching). What do you think?

**Comment by gokul1099** [comment]
Yes, We can incorporate an option in the preferences to allow users to select their default terminal. But for now, we can include a functionality that checks the user's preference. If a preferred terminal is set, the application will open that terminal; otherwise, it will default to the system's default terminal. As we introduce the ability to select the preferred terminal in the future, this functionality will seamlessly align with the new option and adapt accordingly.

**Comment by gokul1099** [comment]
@okwasniewski  hey I need help on this. When I try to open the terminal and run the adb script for opening the logcat the terminal is opened but the adb command is not getting executed and terminal remain empty. I used shellout to with open command              
		try shellOut(to: "open -a \(preferedTermial) --args bash -c\(logcatCommand)")
I also tried using Process to execute this command even in that case terminal open up, but the add command is not getting executed.  Do you have any idea on this ??

**Comment by okwasniewski** [comment]
I think the easiest way to achieve this is with AppleScript:

```
osascript -e 'tell app "Terminal"
    do script "adb logcat -v color"
end tell'
```

Im not sure however how this would work for iTerm

**Comment by gokul1099** [comment]
> I think the easiest way to achieve this is with AppleScript:
> 
> ```
> osascript -e 'tell app "Terminal"
>     do script "adb logcat -v color"
> end tell'
> ```
> 
> Im not sure however how this would work for iTerm

This is working for Terminal in case of iTerm the script should be like 
tell application "Terminal"
	set newWindow to (create window with default profile)
	tell current session of newWindow
		write text "adb -s emulator-5554 logcat -v color"
	end tell
end tell
It is like different script for different terminal.

**Comment by okwasniewski** [comment]
Looks like NSWorkspace is commonly used to open terminal in a certain directory. Just by switching iTerm to Terminal we can achieve terminal opened in different directories. `NSWorkspace.shared.openFile(filePath, withApplication: "iTerm")`

However its not that simple to execute commands. Looks like apple script is the recommended way of doing so. What you could do is create a protocol something like a `Terminal` which would have open() method for each terminal: `iTerm`, `Terminal`, `Hyper` etc. that would run those apple scripts and that way we would have a clean architecture with a way of expanding to new ones.

**Comment by gokul1099** [comment]
@okwasniewski  I have made one pull request please check
