### ISSUE TITLE
New Feature: Display connected devices to allow copying name, udid, or pasting to Android device

### ISSUE THREAD

**Issue by itsramiel** [okwasniewski/MiniSim#121]
Hey,

Would you be interested in also listing connected iOS, Android devices?

A user can then easily know if a device is successfully connected, copy name/udid, and also paste into the android device in case you have text on your computer and you want to paste it into the device

**Comment by okwasniewski** [comment]
Hey, 

I'm up to adding this I think it can be useful!

**Comment by itsramiel** [comment]
On it
