### ISSUE TITLE
ShellOut encountered an error Status code: 127

### ISSUE THREAD

**Issue by suntrop** [okwasniewski/MiniSim#41]
I just installed it via Homebrew and wanted to launch the app, but I got an error only. Similar to https://github.com/okwasniewski/MiniSim/issues/39#issue-1622870506 

MiniSim - ShellOut encountered an error Status code: 127
Message: "/bin/bash: /Users/xyz/Library/Android/sdk/emulator/emulator:
No such file or directory"
Output: ""

Haven't done anything else.

macOS 12.6.3
iMac intel
Never done anything with Android, so I don't know if there is more software needed before using MiniSim.

<img width="803" alt="errormessage" src="https://user-images.githubusercontent.com/1328092/225254826-6f816bb5-cf62-4a28-8f20-a33a293df682.png">

**Comment by okwasniewski** [comment]
Hey @suntrop! 

You need to have proper Android Studio and Xcode setup in order to use the app at the moment. Make sure you can execute those commands: 

To ensure Android setup is correct:
```bash
emulator -help
``` 

To ensure Xcode setup is correct: 
```bash
xcrun simctl
```

**Comment by suntrop** [comment]
Ok, thanks. Didn't see this before. Thought using Homebrew I get this automatically.
