### ISSUE TITLE
Alternative Android SDK path (Homebrew)

### ISSUE THREAD

**Issue by glebosotov** [okwasniewski/MiniSim#44]
When running MiniSim, I get an error saying it could not locate my Android SDK (in `~/Library/Android/...`)

I am using google's `sdkmanager` cli tool to manage the SDK. It was downloaded from Homebrew, the formulae name is `android-commandlinetools`

Default Android SDK root is `/opt/homebrew/share/android-commandlinetools`
However, the locaiton of all executables, including emulators is `~/.android`

Full path to `.avd` files is `~/.android/avd`

Although the **MiniSim.app** is probably looking for `/opt/homebrew/share/android-commandlinetools/emulator/emulator`

Please, enable support for this type of installation, since it is inconvenient to create symlinks.

**Comment by okwasniewski** [comment]
Hello @glebosotov,

The app is looking for the `ANDROID_HOME` variable exported in path. Can you confirm that this variable is set correctly? 

You can do this by running: 

```
echo $ANDROID_HOME
```

**Comment by glebosotov** [comment]
I will check and let you know

**Comment by glebosotov** [comment]
@okwasniewski Works great! 
Thanks
