### ISSUE TITLE
Idea: Raycast Extension for MiniSim

### ISSUE THREAD

**Issue by lyqht** [okwasniewski/MiniSim#46]
Hey there, thanks for this great project! I'm a React Native developer as well, and before stumbling upon this tool, I've been using a [Raycast Simulator Control extension](https://www.raycast.com/noppefoxwolf/simulator-control) for booting up simulators. Sadly it didn't support emulators, so this is a really nice tool to have. 

I like the feature of copying ID/names too so i can install RN apps directly for those simulators 😊

It will be nice if there's a Raycast extension for MiniSim! I do have experience building a Raycast extension so I could help with that, but let me know your thoughts about this idea.

**Comment by okwasniewski** [comment]
Hey @lyqht,

Thanks for opening this issue! Raycast extension is something I'm definitely looking forward to implementing. But firstly on MiniSim side there need to be a way to communicate with Raycast. I've done some research around this topic, and it looks like communicating through Apple Script is the best option. (I saw that Arc browser is doing this: https://github.com/raycast/extensions/tree/94a85235fc605b1ad5eb75ff13bb3fad742b4b07/extensions/arc/) Once I'll have a bit more time, I can implement apple script into MiniSim. And then it will be easier to create extensions for any 3rd party systems. 

I will post my progress around implementing Apple Script in this issue.

**Comment by okwasniewski** [comment]
AppleScript support has been added in [0.7.0](https://github.com/okwasniewski/MiniSim/releases/tag/v0.7.0) 

PR with Raycast extension: https://github.com/raycast/extensions/pull/7978
