### ISSUE TITLE
Android Emulator freezing

### ISSUE THREAD

**Issue by jonathanroze** [okwasniewski/MiniSim#47]
First of all, thanks for this utility is very useful!

But when I launch Emulator with it, emulator freeze few minutes / hours after, I don't have this issue when I launch emu with Android Studio.

I need to quit force, and I got this error

```
MiniSim - ShellOut encountered an error
Status code: 137
Message: "WARNING | cannot add library /Users/user/Library/Android/sdk/emulator/qemu/darwin-aarch64/lib64/vulkan/libvulkan.dylib: failed
WARNING | *** No gRPC protection active, consider launching with the -grpc-use-jwt flag.***
/bin/bash: line
```

Do you have an idea maybe?

**Comment by okwasniewski** [comment]
Hey @jonathanroze, 

Can you check if this is happening on the latest version of Minisim? You can download it here: https://github.com/okwasniewski/MiniSim/releases

I'm not sure why your emulator might get freezes. If you could provide some more details when this happens then I could try to reproduce this and fix it.

**Comment by jonathanroze** [comment]
Hey,

I'm already using 0.4.3

I will try to have more infos!

Thanks

**Comment by okwasniewski** [comment]
Hey @jonathanroze,

Are you still experiencing those issues? Or can I close this issue

**Comment by lucianomlima** [comment]
This is not related to MiniSim. Android emulator freezes here for a React Native app even when opened by Android Studio or terminal. I'm on a Macbook Pro M1 with macOS Ventura 13.4.1

I don't know if is a emulator issue or a React Native issue in Android emulator runnning on ARM macOS

**Comment by okwasniewski** [comment]
@lucianomlima Thanks for confirming, I will close this issue as this is a bug not related to MiniSim.
