### ISSUE TITLE
Refactor `ParametersTable` component to `Table`

### ISSUE THREAD

**Issue by okwasniewski** [okwasniewski/MiniSim#54]
Currently `ParametersTable` uses "custom" implementation of Table due to MacOS 11 as a target. However, with 0.6.0 release MiniSim will support only MacOS 12+ so this component can be refactored.

**Comment by tarunsamanta2k20** [comment]
what changes should I make in refactoring that component?

**Comment by okwasniewski** [comment]
Hey @tarunsamanta2k20, 

Goal of this is to make the `ParametersTable` component use built-in SwiftUI table. Same as custom commands use. The UI to add new parameter can also reflect the same way with `.sheet()` as custom commands have.
