### ISSUE TITLE
how to run ios simulator with commands?

### ISSUE THREAD

**Issue by chj-damon** [okwasniewski/MiniSim#55]
I'm using M2 and xcode Version 14.2 (14C18)， the ios simulator doesn't scroll smoothly. also there no `rosetta` any more.
I have to run this command to make it work:
```
xcrun simctl boot [deviceID] --arch=x86_64
```

is there any way that I can do that by using this app?

**Comment by okwasniewski** [comment]
Hey @chj-damon,

Yes, there is! Using the latest version `0.6.0` you can create custom commands. Just go to settings > Commands and add a new one. 

Here is the snippet for the command: 

```
$xcrun_path simctl boot $uuid --arch=x86_64
```

<img width="794" alt="CleanShot 2023-06-05 at 09 15 51@2x" src="https://github.com/okwasniewski/MiniSim/assets/52801365/c87878be-23f7-4ba5-8291-031926c4c618">

**Comment by chj-damon** [comment]
Thanks, it works perfectly!
