### ISSUE TITLE
How to add a custom command?

### ISSUE THREAD

**Issue by lucianomlima** [okwasniewski/MiniSim#61]
I'm trying to start an Anroid emulator with some custom params. I try to use the following:
```
$android_home_path/emulator/emulator $device_name -feature -Vulkan
```
But I get this error:

<img width="372" alt="Screenshot 2023-06-30 at 14 48 39" src="https://github.com/okwasniewski/MiniSim/assets/1580205/e1a928b5-3b94-4d50-a351-111f5f8afde9">

I'm on Macbook Pro M1 2020 with Ventura 13.4.1

**Comment by okwasniewski** [comment]
Hey, 

The emulator utility requires you to pass device name with an `@` symbol. So the correct syntax for the custom command would be: 

`$android_home_path/emulator/emulator @$device_name -feature -Vulkan`

However, if you want to pass this to every launch command you can use the Android additional launch parameters feature like so:

<img width="762" alt="Screenshot 2023-07-02 at 10 09 51" src="https://github.com/okwasniewski/MiniSim/assets/52801365/4d2bd8af-8156-4eee-b10a-e9159a285c41">
