### ISSUE TITLE
Custom command to boot devices

### ISSUE THREAD

**Issue by chj-damon** [okwasniewski/MiniSim#62]
MiniSim - Custom Command Error 
ShellOut encountered an error
Status code: 149
Message: "An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
Unable to boot device in current state: Booted"
Output: ""

my custom command is : `xcrun simctl boot $uuid --arch=x86_64`

![image](https://github.com/okwasniewski/MiniSim/assets/4902684/4287bcb4-0787-43a3-9ba1-69ec369de657)

**Comment by chj-damon** [comment]
I find out that it's because I've already booted simulator.

I think we may need to add an menu that users can shutdown all booted devices?

**Comment by okwasniewski** [comment]
Hey, 

I think it would make sense to add a way to indicate that a custom command is booting a device - so the command won't be shown for a booted device. I'll keep this issue open until this feature will be added.

**Comment by okwasniewski** [comment]
This has been released in [0.7.0](https://github.com/okwasniewski/MiniSim/releases/tag/v0.7.0)
