### ISSUE TITLE
New feature: allow users to change MiniSim icon

### ISSUE THREAD

**Issue by okwasniewski** [okwasniewski/MiniSim#69]
The goal of this issue is to add new picker to options which would allow users to pick a new menubar icon. 

Similar to the https://maccy.app/

<img width="163" alt="CleanShot 2023-08-27 at 22 21 59@2x" src="https://github.com/okwasniewski/MiniSim/assets/52801365/225a0832-4524-4a72-9db4-c5b845260218">

The available icons would be: 
- Current one (`iphone`) 
- Landscape iPad (`ipad.landscape`)
- Box (`archivebox`)

Names in backticks are the names from SF Symbols. 

Those assets should be placed inside of Assets folder.

**Comment by BrentBoyMeBob** [comment]
I got this functionality running with the aforementioned icons, mind if I can be assigned to this issue? :)
