### ISSUE TITLE
Feature Request: Use it without Android SDK

### ISSUE THREAD

**Issue by suleymanbariseser** [okwasniewski/MiniSim#71]
I want to use MiniSim only for IOS simulators for now. However, application crashes if I do not have the Android SDK. Is there any chance to make it work without Android SDK?

![Screenshot 2023-09-10 at 21 25 04](https://github.com/okwasniewski/MiniSim/assets/50797736/29f44f91-8b64-4eed-9915-33eac23da34d)

**Comment by discocoffeeeee** [comment]
up .. , we need it .

**Comment by okwasniewski** [comment]
Hey, thanks for opening the issue! This is a feature Im looking forward in this app. I will keep this issue open until its released. 

PS. Contributions are welcome 😄
