### ISSUE TITLE
Add SwiftLint to codebase

### ISSUE THREAD

**Issue by okwasniewski** [okwasniewski/MiniSim#86]
The goal of this issue is to add `SwiftLint` to the codebase to make code more consistent.

https://github.com/realm/SwiftLint

**Comment by Garfeild** [comment]
I can help with that. Would you be up to add Github Action to prevent merging inconsistent code? Usually, it's only way to ensure no inconsistent code is merged.

**Comment by okwasniewski** [comment]
@Garfeild Project script + CI running on every PR would be ideal setup 👍🏻

**Comment by Garfeild** [comment]
I have tried to integrate SwiftLint as [plugin](https://github.com/realm/SwiftLint#plug-in-support). There are some pros and cons with such integration.

Pros:
* It shows warning/errors during compilation time in Xcode directly.
* It's easy to share with any contributor and harder to disable.

Cons
* It lints whole project and couldn't lint only changed files. This is not visible for current state of the project (takes 0.17s).
* Until we fix all warnings, build log will be polluted with them. Easy to miss important warnings.
    * After I cleaned up everything, it was 4 warnings.

Personally, I think it gives us good start and we can ignore first problem and mitigate second. And I would still introduce CI check.
