### ISSUE TITLE
Enable `no_magic_numbers` SwiftLint rule

### ISSUE THREAD

**Issue by okwasniewski** [okwasniewski/MiniSim#95]
The goal of this PR is to enable `no_magic_numbers` SwiftLint rule and refactor pieces of the app to make SwiftLint happy.

**Comment by caseycharleston** [comment]
Hello! If this issue still persists, I would be happy to help.

**Comment by okwasniewski** [comment]
Yeah the issue is still there so pick it up if you want 😄
